

let tvshows = [
  "20/20",
  "21 Jump Street",
  "24",
  "2DTV",
  "30 Rock",
  "31 Minutes",
  "50 Cent: The Money and the Power",
  "50/50",
  "64 Zoo Lane",
  "6teen",
  "704 Hauser",
  "8 Simple Rules",
  "8th & Ocean",
  "A Class by Himself",
  "A Pup Named Scooby-Doo",
  "ANT Farm",
  "Access Hollywood",
  "According to Jim",
  "Ace Lightning",
  "Acme Hour",
  "Action",
  "Active Kids",
  "Adam's Rib",
  "Adventures in Paradise",
  "Airwolf",
  "Alcatraz",
  "Alfred J. Kwak",
  "Alias Smith and Jones",
  "Aliens in America",
  "All Is Forgiven",
  "Almost Human (TV series)",
  "Amazing Stories",
  "Amen",
  "America's Funniest Home Videos",
  "America's Funniest People",
  "American Chopper",
  "American Dragon: Jake Long",
  "American High",
  "American Pickers",
  "An Idiot Abroad",
  "Andromeda",
  "Andy Richter Controls the Universe",
  "Angel",
  "Anger Management",
  "Angry Beavers",
  "Animaniacs",
  "Animorphs",
  "Another World",
  "Any Dream Will Do",
  "Anything You Can Do",
  "Archie's Weird Mysteries",
  "Are You Smarter Than a 5th Grader?",
  "Ark II",
  "Arnie",
  "Arrow",
  "Arthur Godfrey and His Friends",
  "As Told By Ginger",
  "Australia's Next Top Model",
  "Awkward",
  "Baa Baa Black Sheep",
  "Babestation",
  "Baby Daddy",
  "Bachelor Father",
  "Bagpuss",
  "Banshee",
  "Barefoot in the Park",
  "Baretta",
  "Barnaby Jones",
  "Basil Brush",
  "Batfink",
  "Bayly (TV series)",
  "Baywatch Nights",
  "Beadle's About",
  "Beat The Chef",
  "Beating Heart",
  "Beetlejuice",
  "Behind the Music",
  "Being Human",
  "Belle and Sebastian (TV series)",
  "Bem-Vindos a Beirais",
  "Ben 10",
  "Ben 10: Ultimate Alien",
  "Benson",
  "Besame Tonto",
  "Beverly Hills, 90210",
  "Bewitched",
  "Big Arvo",
  "Big Town",
  "Billy",
  "Bionic Woman",
  "Birds of Prey",
  "Black Books",
  "Blake's 7",
  "Bless This House",
  "Blockbusters",
  "Blonde Charity Mafia",
  "Blue Heelers",
  "Blue Mountain State",
  "Blue Peter",
  "Boardwalk Empire",
  "Bob Hope Presents the Chrysler Theatre",
  "Bob Patterson",
  "BodyShaping",
  "Bones",
  "Boot Camp",
  "Borgia",
  "Boston Public",
  "Boy Meets World",
  "Branded",
  "Brat Camp",
  "Breaking Bad",
  "Breakout Kings",
  "Britain's Missing Top Model",
  "Brooke Knows Best",
  "Brotherly Love",
  "Brothers & Sisters",
  "Bubble Guppies",
  "Buck Rogers in the 25th Century",
  "Buck Rogers",
  "Bug Juice",
  "Bullseye",
  "Busting Loose",
  "C.O.P.S.",
  "C.P.O. Sharkey",
  "CI5: The New Professionals",
  "Cade's County",
  "Caesar's Hour",
  "Caillou",
  "Caitlin's Way",
  "Cake Boss",
  "Californication",
  "Camp Lazlo",
  "Camp Runamuck",
  "Camp",
  "Canadian Idol",
  "Cannon",
  "Cannonball",
  "Canterbury's Law",
  "Caprica",
  "Captain Caveman and the Teen Angels",
  "Captain Kangaroo",
  "Captain Planet and the Planeteers",
  "Captain Power",
  "Caribe",
  "Cash Cab",
  "CatDog",
  "Catalyst",
  "Catwalk",
  "Celebrity Rehab with Dr. Drew",
  "Centennial",
  "Chain Reaction",
  "ChalkZone",
  "Charlie Chalk",
  "Charlie Jade",
  "Charlie Rose",
  "Cheez TV",
  "Cheyenne",
  "Chicago Hope",
  "Child's Play",
  "China Beach",
  "Chopped",
  "Ciao Darwin",
  "City Lights",
  "Clangers",
  "Class of '74",
  "Clerks: The Animated Series",
  "Clone High",
  "Club Mario",
  "Clueless",
  "Co-Ed Fever",
  "Code Lyoko",
  "Codename: Kids Next Door",
  "Cold Case",
  "Cold Feet",
  "Colditz",
  "Columbo",
  "Commander in Chief",
  "Contraption",
  "Coronet Blue",
  "Cory in the House",
  "Cosmetic Surgery Live",
  "Countdown",
  "Country Style",
  "Countrytime (1960)",
  "Countrytime (1970)",
  "Cousin Skeeter",
  "Cover Up",
  "Cracking Up",
  "Criminal Minds",
  "Crossbow",
  "Crusade",
  "Cupcake Wars",
  "Curb Your Enthusiasm",
  "Da Ali G Show",
  "DaVinci's Inquest",
  "Dad's Army",
  "Damages",
  "Dan August",
  "Dance Academy",
  "Danger 5",
  "Danger Man",
  "Danny Phantom",
  "Darkwing Duck",
  "Dave Allen",
  "Dead of NIght",
  "Dear Sister",
  "Decisiones",
  "Demons",
  "Denkigai no Honya-san",
  "Desperate Housewives",
  "Dharma and Greg",
  "Dirty Sally",
  "Doctors (soap opera)",
  "Dog Bites Man",
  "Don't Forget Your Toothbrush",
  "Donny & Marie",
  "Doogie Howser, M.D.",
  "Double Trouble",
  "Dr. Finlay's Casebook",
  "Dr. Kildare",
  "Dr. Quinn, Medicine Woman",
  "Dragon Ball",
  "Duck Dynasty",
  "Due South",
  "E Street",
  "E/R",
  "ECW on Syfy",
  "ECW on TNN",
  "EZ Streets",
  "Earth 2",
  "Earth Revealed: Introductory Geology",
  "EastEnders",
  "Eastbound & Down",
  "Eastwick",
  "Ed, Edd, and Eddy",
  "Eddy Arnold Time",
  "Eerie, Indiana",
  "Eight is Enough",
  "Electra Woman and Dyna Girl",
  "Elementary",
  "Eleventh Hour",
  "Eli Stone",
  "Elizabeth R",
  "Emmerdale",
  "Engine Sentai Go-Onger",
  "Entourage",
  "Eric Sykes",
  "Eternal Law",
  "Eureka",
  "Everwood",
  "Extreme Dodgeball",
  "Extreme Makeover: Home Edition",
  "Eyewitness",
  "F Troop",
  "Falcon Crest",
  "Falling Skies",
  "Family Challenge",
  "Family Fortunes",
  "Family Guy",
  "Family Ties",
  "Family",
  "Farscape",
  "Fashion House",
  "Fast Money",
  "Fat Albert and the Cosby Kids",
  "Fat Guy Stuck in Internet",
  "Father Murphy",
  "Felicity",
  "Firefly",
  "Five Fingers",
  "Flamingo Road",
  "Flash Forward",
  "FlashForward",
  "Flashpoint",
  "Flavor Of Love",
  "Flight 29 Down",
  "Flight of the Conchords",
  "Flikken",
  "Flower Pot Men",
  "Flying Rhino Junior High",
  "Food Network Challenge",
  "Football Superstar",
  "Forgive or Forget",
  "Foster's Home for Imaginary Friends",
  "Fraggle Rock",
  "Franklin",
  "FreakyLinks",
  "Freewheelers",
  "Fresh Meat",
  "Friday Night Lights",
  "Fridays",
  "Friend or Foe?",
  "Friends",
  "Friendzone",
  "Fringe",
  "Frontier Justice",
  "Frontier",
  "Full House",
  "Futurama",
  "Future Weapons",
  "G-Saviour",
  "Gadget Boy & Heather",
  "Gal Circle",
  "Galactica 1980",
  "Gamezville",
  "Garfield and Friends",
  "Gargoyles",
  "General Hospital",
  "Gentle Touch",
  "George Lopez",
  "George Shrinks",
  "Get Smart",
  "Ghost Story",
  "Ghost Trackers",
  "Ghostwriter",
  "Gilligan's Island",
  "Glee",
  "Glenn Beck",
  "Going Places",
  "Gomer Pyle, U.S.M.C.",
  "Good Luck Charlie",
  "Good Morning, Mickey!",
  "Gravity Falls",
  "Grim & Evil",
  "Grim Adventures of Billy and Mandy",
  "Grimm",
  "Gunslinger Girl",
  "Half & Half",
  "Happy Endings",
  "Happy Tree Friends",
  "Hardcastle and McCormick",
  "Harper's Island",
  "Hart of Dixie",
  "Hart to Hart",
  "Harvey Birdman, Attorney at Law",
  "Have Gun - Will Travel",
  "Haven",
  "Hawaii Five-0",
  "Hawkins",
  "He-Man and the Masters of the Universe",
  "Hell's Kitchen (U.S. TV series)",
  "Here We Go Again",
  "Hergé's Adventures of Tintin",
  "Heston's Feasts",
  "Hey Vern, It's Ernest!",
  "Hi Hi Puffy AmiYumi",
  "Hitchhikers Guide To The Galaxy",
  "Hollywood Heights",
  "Home Improvement",
  "Hope & Faith",
  "Hot L Baltimore",
  "Hotel",
  "House of Cards",
  "House of Lies",
  "How It's Made",
  "Huff",
  "Human Target",
  "Hunter",
  "Hustle",
  "I Pity the Fool",
  "I'm In The Band",
  "In Living Color",
  "Inquizition",
  "Inspector Gadget",
  "Intervention",
  "Iron Chef America",
  "Iron Chef",
  "Ironside",
  "It Takes a Thief",
  "It's Garry Shandling's Show",
  "It's a Miracle",
  "Ivanhoe",
  "JONAS",
  "Jack of All Trades (TV series)",
  "Jackie Chan Adventures",
  "Jake and the Never Land Pirates",
  "Jason King",
  "Jem (TV series)",
  "Jep!",
  "Jeremiah",
  "Jersey Shore",
  "Jerseylicious",
  "Jimmy Kimmel Live!",
  "Joe Millionaire",
  "John Adams",
  "Johnny Bravo",
  "Joking Apart",
  "Josie and the Pussycats",
  "Jubilee USA",
  "Judge Joe Brown",
  "Juke Box Jury",
  "Juken Sentai Gekiranger",
  "Julia",
  "Julie",
  "Just Jordan",
  "Just Shoot Me!",
  "Justice League",
  "Kablam!",
  "Kaiketsu Zorro",
  "Kaiki Renai Sakusen",
  "Karen",
  "Kathy",
  "Keeping Up Appearances",
  "Keeping Up with the Kardashians",
  "Kenan & Kel",
  "Kickin' It",
  "Kids Incorporated",
  "Killer Instinct",
  "Kimba the White Lion",
  "Kitchen Confidential",
  "Knightmare",
  "Knowing Me, Knowing You",
  "Kolchak: The Night Stalker",
  "Kourtney and Khloé Take Miami",
  "Kraft Television Theatre",
  "Krypto the Superdog",
  "Kung Fu Panda",
  "Kyle XY",
  "L.A. Law",
  "Lab Rats",
  "Land of the Giants",
  "Land of the Lost",
  "Larry King Live",
  "Lassie",
  "Last Man Standing",
  "Late Night with Conan O'Brien",
  "Later with Bob Costas",
  "Law & Order: Trial by Jury",
  "Legend of the Seeker",
  "Lidsville",
  "Life Goes On",
  "Life Is Wild",
  "Life on Mars",
  "Life with Boys",
  "Life with Derek",
  "Life with Lucy",
  "Lifestyles of the Rich and Famous",
  "Lightning Point",
  "Lingo",
  "Little Einsteins",
  "Little People, Big World",
  "Live with Regis and Kathie Lee",
  "Live with Regis and Kelly",
  "Living Single",
  "Lizzie McGuire",
  "Location, Location, Location",
  "Loft Story",
  "Logan's Run",
  "Longstreet",
  "Lost",
  "Love & War",
  "Love Connection",
  "Love of Life",
  "Love, Sidney",
  "Lucky Louie",
  "Lunch with Soupy Sales",
  "MANswers",
  "Mad Men",
  "Made",
  "Maggie",
  "Make Room for Daddy",
  "Making Fiends",
  "Man About the House",
  "Man from Atlantis",
  "Man in a Suitcase",
  "Manhunt",
  "Manimal",
  "Mark Twain",
  "Married by America",
  "Marshall Law",
  "Martha Speaks",
  "Martial Law",
  "Martin Kane, Private Eye",
  "Mary Kay and Johnny",
  "Mary",
  "Masterpiece Theatre",
  "Maury",
  "Mayberry R.F.D.",
  "McCloud",
  "McHale's Navy",
  "McMorris & McMorris",
  "Me and My Monsters",
  "Meet Millie",
  "Meet the Browns",
  "Melody Rules",
  "Men Behaving Badly",
  "Men, Women & Dogs",
  "Metal Mickey",
  "Mickey Mouse Club",
  "Midnight Caller",
  "Mighty Max",
  "Mighty Morphin Power Rangers",
  "Ministry Of Mayhem",
  "Miss Fisher's Murder Mysteries",
  "Miss Marple",
  "Miss Match",
  "Mister Ed",
  "Mobile Suit Gundam 0083: Stardust Memory",
  "Monkey",
  "Monsters",
  "Moonlighting",
  "Mortal Kombat: Conquest",
  "Mr. & Mrs. Smith",
  "Mr. Adams and Eve",
  "Mr. Meaty",
  "Mr. Novak",
  "Mr. Peepers",
  "Mr. Sunshine",
  "Mr. Young",
  "Muktha",
  "Murder, She Wrote",
  "Must Love Kids",
  "Mutant X",
  "My Big Fat Obnoxious Boss",
  "My Boys",
  "My Family's Got GUTS",
  "My Favorite Martian",
  "My Kitchen Rules",
  "My Little Pony",
  "My Little Pony: Friendship Is Magic",
  "My Name Is Earl",
  "My Secret Identity",
  "My Wife and Kids",
  "My World and Welcome to It",
  "Mysterious Ways",
  "N.Y.P.D.",
  "NCIS",
  "NCIS: Los Angeles",
  "NYPD Blue",
  "Name That Tune",
  "National Bingo Night",
  "Ned and Stacey",
  "Needles and Pins",
  "Next",
  "Nine to Five",
  "North Shore",
  "Northern Exposure",
  "Not the Nine O'Clock News",
  "Nothing Sacred",
  "Noticentro 4",
  "Nowhere Man",
  "Number Please",
  "Nurse Jackie",
  "Nurses",
  "O2Be",
  "Ocean Girl",
  "Oddville, MTV",
  "Oggy and the Cockroaches",
  "Omnibus",
  "On the Rocks",
  "Once Upon a Time in Wonderland",
  "Once and Again",
  "One Day at a Time",
  "One Foot in the Grave",
  "One Tree Hill",
  "Online Nation",
  "Oobi",
  "Opposite Sex",
  "Our Friends in the North",
  "Our Miss Brooks",
  "Over There",
  "Ozark Jubilee",
  "Packed to the Rafters",
  "Pair of Kings",
  "Pan Am",
  "Panorama",
  "Parker Lewis Can't Lose",
  "Pass the Buck",
  "Password Plus",
  "Password",
  "Perfect Couples",
  "Perfect Hair Forever",
  "Pet Alien",
  "Peter Gunn",
  "Petticoat Junction",
  "Phil of the Future",
  "Pinky and the Brain",
  "Play the Percentages",
  "Please Don't Eat the Daisies",
  "Plonsters",
  "Pocoyo",
  "Pole Position (TV series)",
  "Police Ten 7",
  "Police Women of Maricopa County",
  "Politically Incorrect",
  "Pop! Goes the Country",
  "Pororo the Little Penguin",
  "Power Rangers Dino Thunder",
  "Power Rangers Jungle Fury",
  "Power Rangers Lost Galaxy",
  "Power Rangers Operation Overdrive",
  "Power Rangers S.P.D.",
  "Power Rangers Time Force",
  "Power Rangers in Space",
  "Prank Patrol",
  "Pranked",
  "Pretty Wild",
  "Prison Break",
  "Prisoners of Gravity",
  "Project G.e.e.K.e.R.",
  "Protagonistas De La Musica",
  "Puberty Blues",
  "Punk'd",
  "Punky Brewster",
  "Pushing Daisies",
  "Pussycat Dolls Present",
  "QI",
  "Quantum Leap",
  "Quatermass",
  "Que Locura",
  "Queen of Swords",
  "Queer Eye for the Straight Guy",
  "Quick Before They Catch Us",
  "Quintuplets",
  "Ramar of the Jungle",
  "Rawhide",
  "Real People",
  "Real Time with Bill Maher",
  "Real World/Road Rules Challenge",
  "Reaper",
  "Reba",
  "Rebelde Way",
  "Reborn!",
  "Rebound",
  "Red Dwarf",
  "Regular Show",
  "Relic Hunter",
  'Ren & Stimpy "Adult Party Cartoon"',
  "Rentaghost",
  "Rescue 8",
  "Return to Peyton Place",
  "Reunion",
  "Revenge",
  "Revolution",
  "Rhoda",
  "Riptide",
  "Rob & Big",
  "Rob Dyrdek's Fantasy Factory",
  "Robin Hood",
  "Rocket Robin Hood",
  "Roots: The Next Generations",
  "Ros na Rún",
  "Roseanne",
  "Route 66",
  "Rowan & Martin's Laugh-In",
  "Rubik the Amazing Cube",
  "Run Joe Run",
  "Run for Your Life",
  "Rurouni Kenshin",
  "Ryan",
  "Ryan's Hope",
  "S.W.A.T.",
  "SWAT Kats: The Radical Squadron",
  "Sabrina, The Animated Series",
  "Sadie J",
  "Sally",
  "Salute Your Shorts",
  "Sam",
  "Sanctuary",
  "Sanford and Son",
  "Saturday Night Live",
  "Saved by the Bell",
  "Saved by the Bell: The New Class",
  "Scandal",
  "Scarecrow and Mrs. King",
  "Scaredy Squirrel",
  "Schoolhouse Rock!",
  "Science Fiction Theatre",
  "Scooby-Doo, Where Are You!",
  "Scoop and Doozie",
  "Scrabble",
  "Sea Hunt",
  "SeaQuest DSV",
  "Secret Agent",
  "See It Now",
  "Seeing Things",
  "She-Ra: Princess of Power",
  "Sherlock",
  "Silver Spoons",
  "Simon & Simon",
  "Sing Along with Mitch",
  "Sir Francis Drake",
  "Sister, Sister",
  "Sisters",
  "Sleeper Cell",
  "So Little Time",
  "So Random",
  "Soap",
  "Sofia the First",
  "Solid Gold",
  "Something So Right",
  "Sonny with a Chance",
  "Sons of Anarchy",
  "South Park",
  "South of Nowhere",
  "Southland",
  "Space Patrol",
  "Space: 1999",
  "Spaced",
  "Spartakus and the Sun Beneath the Sea",
  "Speed Racer",
  "Spenser: For Hire",
  "Spider-Man: The New Animated Series",
  "SportsCenter",
  "Square Pegs",
  "St. Elsewhere",
  "Standoff",
  "Star Trek: Phase II",
  "Star Wars: Droids",
  "Stargate SG-1",
  "Starsky and Hutch",
  "Stingray",
  "Strangers with Candy",
  "Strike It Rich",
  "Strömsö",
  "Super Friends",
  "Super Greed",
  "Super Jeopardy!",
  "Supercar",
  "Supernatural",
  "Swamp Thing",
  "Switch",
  "T. J. Hooker",
  "TV Funhouse",
  "TV's Bloopers & Practical Jokes",
  "Take the High Road",
  "Takin' Over the Asylum",
  "TaleSpin",
  "Tallship Chronicles",
  "Team Umizoomi",
  "Teen Mom 2",
  "Teen Mom",
  "Teen Titans",
  "Terminator: The Sarah Connor Chronicles",
  "Terra Nova",
  "Terry and June",
  "Texaco Star Theater",
  "Texas Country Reporter",
  "That '80s Show",
  "That's My Mama",
  "That's the Question",
  "The 4400",
  "The Adventures of Jimmy Neutron: Boy Genius",
  "The Adventures of Pete & Pete",
  "The Adventures of Wild Bill Hickok",
  "The Adventures of William Tell",
  "The Alan Young Show",
  "The American Embassy",
  "The Avengers",
  "The Backyardigans",
  "The Barbara Stanwyck Show",
  "The Baron",
  "The Beachcombers",
  "The Benny Hill Show",
  "The Big Gig",
  "The Bionic Woman",
  "The Black Donnellys",
  "The Blacklist",
  "The Block",
  "The Bold and the Beautiful",
  "The Boondocks",
  "The Borgias",
  "The Brady Brides",
  "The Brothers",
  "The Bugaloos",
  "The Bugs Bunny Show",
  "The Buzz on Maggie",
  "The Cape",
  "The Carol Burnett Show",
  "The Catherine Tate Show",
  "The Celebrity Apprentice",
  "The Champions",
  "The Colbert Report",
  "The Colony",
  "The Cowboys",
  "The Crew",
  "The Crocodile Hunter",
  "The Curse of Oak Island",
  "The D.A.",
  "The Daily Show",
  "The Dr. Oz Show",
  "The Duck Factory",
  "The Dukes of Hazzard",
  "The Electric Company",
  "The Ellen DeGeneres Show",
  "The Ellen Show",
  "The Emperor's New School",
  "The Equalizer",
  "The F.B.I.",
  "The Face Is Familiar",
  "The Fast Show",
  "The Forgotten",
  "The Fosters",
  "The Four Just Men",
  "The Gene Autry Show",
  "The Generations Project",
  "The Ghost & Mrs. Muir",
  "The Good Guys",
  "The Governor and J.J.",
  "The Great Space Coaster",
  "The Heartland Series",
  "The Islanders",
  "The Jamie Foxx Show",
  "The Jay Leno Show",
  "The Jerry Springer Show",
  "The Jetsons",
  "The Jim Nabors Hour",
  "The Jimmy Dean Show",
  "The Joe Schmo Show",
  "The Joker's Wild",
  "The Kids in the Hall",
  "The Kids in the Hall: Death Comes to Town",
  "The King of Queens",
  "The League of Gentlemen",
  "The Letter People",
  "The Living Century",
  "The Lone Ranger",
  "The Loner",
  "The Loretta Young Show",
  "The Lost Room",
  "The Magic Hour",
  "The Magician",
  "The Magnificent Seven",
  "The Man Show",
  "The Man from U.N.C.L.E.",
  "The Mary Tyler Moore Hour",
  "The Merv Griffin Show",
  "The Middleman",
  "The Midnight Special",
  "The Mighty B!",
  "The Millionaire",
  "The Milton Berle Show",
  "The Mod Squad",
  "The Mole",
  "The Monroes",
  "The Munsters",
  "The Muppet Show",
  "The NBC Mystery Movie",
  "The New Adventures of Pinocchio",
  "The New Adventures of Zorro",
  "The New Dick Van Dyke Show",
  "The New Perry Mason",
  "The Newlywed Game",
  "The Nurses",
  "The O.C.",
  "The O'Reilly Factor",
  "The Odd Couple",
  "The Osbournes",
  "The PJs",
  "The Paradise",
  "The Parent 'Hood",
  "The Persuaders!",
  "The Phil Silvers Show",
  "The Price Is Right",
  "The Protectors",
  "The Psychiatrist",
  "The Quatermass Experiment",
  "The Rat Patrol",
  "The Real Adventures of Jonny Quest",
  "The Real Housewives of Beverly Hills",
  "The Real Housewives of D.C.",
  "The Rebel Billionaire: Branson's Quest for the Best",
  "The Ren & Stimpy Show",
  "The Restaurant",
  "The Restless Years",
  "The Rich List",
  "The Riches",
  "The Rifleman",
  "The Saddle Club",
  "The Sentimental Agent",
  "The Six Million Dollar Man",
  "The Smothers Brothers Comedy Hour",
  "The Spectacular Spider-Man",
  "The Sunday Comics",
  "The Super Mario Bros. Super Show!",
  "The Super",
  "The Surreal Life",
  "The Sword in the Stone",
  "The Tick",
  "The Tony Danza Show",
  "The Tortellis",
  "The Venture Bros.",
  "The Wallace and Ladmo Show",
  "The Walter Winchell Show",
  "The War at Home",
  "The Weakest Link",
  "The Wild Wild West",
  "The Wizard",
  "The Woodlanders",
  "The X Factor",
  "The Zoo Gang",
  "The_Librarians_(2014_TV_series)",
  "They Came from Outer Space",
  "Thicker than Water",
  "This Hour Has 22 Minutes",
  "Three Rivers",
  "Three's Company",
  "Threshold",
  "Thriller",
  "Thunderbirds",
  "Thundercats",
  "Tic-Tac-Dough",
  "Tim and Eric Nite Live!",
  "Tiny Toon Adventures",
  "Tiswas",
  "Titus",
  "Today on the Farm",
  "Today's Special",
  "Top Of The Pops",
  "Tosh.0",
  "Total Drama Action",
  "Total Drama: Revenge of the Island",
  "Totally Spies",
  "Touching Evil",
  "Tough Crowd with Colin Quinn",
  "Tour of Duty",
  "Tower Prep",
  "Trapper John, M.D.",
  "Trinity Blood",
  "Trivia Track",
  "TruTV Presents: World's Dumbest...",
  "True Blood",
  "True Jackson: VP",
  "Twenty One",
  "Twenty Questions",
  "Two Pints of Lager and a Packet of Crisps",
  "Two for the Money",
  "Ultimate Force",
  "Ultraman",
  "Ulysses 31",
  "Under the Dome",
  "United States of Tara",
  "Until Tomorrow",
  "Utopia",
  "V",
  "V: The Final Battle",
  "Van Der Valk",
  "Veep",
  "Veronica Mars",
  "Victorious",
  "Vikings",
  "Voltron: Defender of the Universe",
  "Walker, Texas Ranger",
  "Wanted: Dead or Alive",
  "Warehouse 13",
  "Wayside",
  "Webster",
  "Weeds",
  "West Point Story",
  "Whammy! The All-New Press Your Luck",
  "What the Papers Say",
  "What's Happening!!",
  "Whatever Happened to Robot Jones?",
  "Wheel of Fortune 2000",
  "Wheel of Fortune",
  "When Games Attack",
  "Whiplash",
  "Who Wants to Be a Millionaire?",
  "Who Wants to Be a Superhero?",
  "Who Wants to Marry My Dad?",
  "Who's the Boss?",
  "Wife Swap",
  "Wild On!",
  "Win, Lose or Draw",
  "Winning Streak",
  "Wire in the Blood",
  "With This Ring",
  "Wizards of Waverly Place",
  "Women's Murder Club",
  "Wonder Showzen",
  "Wonderfalls",
  "Workaholics",
  "Working Girl",
  "World Blackjack Tour",
  "World's Most Amazing Videos",
  "World's Wildest Police Videos",
  "Yancy Derringer",
  "Yes Minister",
  "Yin Yang Yo!",
  "Yogi's Gang",
  "You Asked For It",
  "You Bet Your Life",
  "You Can't Do That on Television",
  "Your Hit Parade",
  "Yu-Gi-Oh! 5D's",
  "Yu-Gi-Oh! Arc V",
  "Yu-Gi-Oh! GX",
  "ZOOM",
  "Zoids",
  "Zoobilee Zoo",
  "Zooboomafoo",
  "Zorro and Son",
  "Zorro",
  "Zorro: Generation Z",
  "Zorro: La Espada y la Rosa",
  "Zumbo",
  "'Allo 'Allo!",
  "'Til Death",
  "Óli á Hrauni"
];

let movies = [
  "The Godfather (1972)",
  "Schindler's List (1993)",
  "Raging Bull (1980)",
  "Casablanca (1942)",
  "Citizen Kane (1941)",
  "Gone with the Wind (1939)",
  "The Wizard of Oz (1939)",
  "One Flew Over the Cuckoo's Nest (1975)",
  "Lawrence of Arabia (1962)",
  "Vertigo (1958)",
  "Psycho (1960)",
  "The Godfather: Part II (1974)",
  "On the Waterfront (1954)",
  "Forrest Gump (1994)",
  "The Sound of Music (1965)",
  "12 Angry Men (1957)",
  "West Side Story (1961)",
  "Star Wars: Episode IV - A New Hope (1977)",
  "2001: A Space Odyssey (1968)",
  "Chinatown (1974)",
  "Singin' in the Rain (1952)",
  "It's a Wonderful Life (1946)",
  "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964)",
  "Some Like It Hot (1959)",
  "Ben-Hur (1959)",
  "Apocalypse Now (1979)",
  "Amadeus (1984)",
  "The Lord of the Rings: The Return of the King (2003)",
  "Gladiator (2000)",
  "Unforgiven (1992)",
  "Raiders of the Lost Ark (1981)",
  "Rocky (1976)",
  "A Streetcar Named Desire (1951)",
  "To Kill a Mockingbird (1962)",
  "My Fair Lady (1964)",
  "A Clockwork Orange (1971)",
  "Doctor Zhivago (1965)",
  "The Searchers (1956)",
  "Jaws (1975)",
  "Patton (1970)",
  "Butch Cassidy and the Sundance Kid (1969)",
  "The Good, the Bad and the Ugly (1966)",
  "The Apartment (1960)",
  "Platoon (1986)",
  "Braveheart (1995)",
  "Dances with Wolves (1990)",
  "The Exorcist (1973)",
  "The Pianist (2002)",
  "Goodfellas (1990)",
  "The Deer Hunter (1978)",
  "All Quiet on the Western Front (1930)",
  "Bonnie and Clyde (1967)",
  "The French Connection (1971)",
  "Midnight Cowboy (1969)",
  "Mr. Smith Goes to Washington (1939)",
  "Rain Man (1988)",
  "Annie Hall (1977)",
  "Fargo (1996)",
  "Close Encounters of the Third Kind (1977)",
  "Nashville (1975)",
  "Network (1976)",
  "The Graduate (1967)",
  "American Graffiti (1973)",
  "Pulp Fiction (1994)",
  "Terms of Endearment (1983)",
  "The Great Dictator (1940)",
  "Double Indemnity (1944)",
  "The Maltese Falcon (1941)",
  "Taxi Driver (1976)",
  "Rear Window (1954)",
  "The Third Man (1949)",
  "Rebel Without a Cause (1955)",
  "North by Northwest (1959)",
  "Tom Jones (1963)",
  "A Man for All Seasons (1966)",
  "In the Heat of the Night (1967)",
  "Oliver! (1968)",
  "The Sting (1973)",
  "One Flew Over The Cuckoo's Nest (1975)",
  "Kramer vs. Kramer (1979)",
  "Ordinary People (1980)",
  "Chariots of Fire (1981)",
  "Gandhi (1982)",
  "Out of Africa (1985)",
  "The Last Emperor (1987)",
  "Driving Miss Daisy (1989)",
  "The English Patient (1996)",
  "Shakespeare in Love (1998)",
  "American Beauty (1999)",
  "A Beautiful Mind (2001)",
  "Chicago (2002)",
  "Million Dollar Baby (2004)",
  "Crash (2005)",
  "The Departed (2006)",
  "No Country for Old Men (2007)",
  "Slumdog Millionaire (2008)",
  "The Hurt Locker (2009)",
  "The King's Speech (2010)",
  "The Artist (2011)",
  "Argo (2012)",
  "12 Years a Slave (2013)",
  "Birdman (2014)",
  "Spotlight (2015)",
  "Moonlight (2016)",
  "The Shape of Water (2017)",
  "Black Swan (2010)",
  "Inception (2010)",
  "The Social Network (2010)",
  "Toy Story 3 (2010)",
  "True Grit (2010)",
  "Moneyball (2011)",
  "War Horse (2011)",
  "Life of Pi (2012)",
  "Silver Linings Playbook (2012)",
  "Zero Dark Thirty (2012)",
  "Dallas Buyers Club (2013)",
  "Gravity (2013)",
  "Her (2013)",
  "The Wolf of Wall Street (2013)",
  "Birdman or (The Unexpected Virtue of Ignorance) (2014)",
  "American Sniper (2014)",
  "Boyhood (2014)",
  "The Grand Budapest Hotel (2014)",
  "The Imitation Game (2014)",
  "Selma (2014)",
  "Whiplash (2014)",
  "The Big Short (2015)",
  "Mad Max: Fury Road (2015)",
  "The Martian (2015)",
  "The Revenant (2015)",
  "Arrival (2016)",
  "Hidden Figures (2016)",
  "La La Land (2016)",
  "Manchester by the Sea (2016)",
  "Call Me by Your Name (2017)",
  "Darkest Hour (2017)",
  "Dunkirk (2017)",
  "Get Out (2017)",
  "Lady Bird (2017)",
  "Phantom Thread (2017)",
  "The Post (2017)",
  "Three Billboards Outside Ebbing, Missouri (2017)",
  "Chocolat (2000)",
  "Crouching Tiger, Hidden Dragon (2000)",
  "Erin Brockovich (2000)",
  "Traffic (2000)",
  "The Lord of the Rings: The Fellowship of the Ring (2001)",
  "Moulin Rouge! (2001)",
  "Gangs of New York (2002)",
  "The Hours (2002)",
  "The Lord of the Rings: The Two Towers (2002)",
  "Lost in Translation (2003)",
  "Master and Commander: The Far Side of the World (2003)",
  "Mystic River (2003)",
  "Seabiscuit (2003)",
  "Sideways (2004)",
  "Brokeback Mountain (2005)",
  "Capote (2005)",
  "Good Night, and Good Luck (2005)",
  "Little Miss Sunshine (2006)",
  "Juno (2007)",
  "There Will Be Blood (2007)",
  "The Curious Case of Benjamin Button (2008)",
  "Avatar (2009)",
  "District 9 (2009)",
  "Inglourious Basterds (2009)",
  "Up (2009)",
  "Blade Runner (1982)",
  "Beetlejuice (1988)",
  "Ghostbusters (1984)",
  "Back to the Future (1985)",
  "The Princess Bride (1987)",
  "The Goonies (1985)",
  "The Shining (1980)",
  "Full Metal Jacket (1987)",
  "Top Gun (1986)",
  "The Outsiders (1983)",
  "Uncle Buck (1989)",
  "The Karate Kid (1984)",
  "E.T. the Extra-Terrestrial (1982)",
  "The Breakfast Club (1985)",
  "Dune (1984)",
  "Aliens (1986)",
  "Stand by Me (1986)",
  "Scarface (1983)",
  "Road House (1989)",
  "Die Hard (1988)",
  "Dirty Dancing (1987)",
  "Batman (1989)",
  "Star Wars: Episode VI - Return of the Jedi (1983)",
  "Star Wars: Episode V - The Empire Strikes Back (1980)",
  "Ferris Bueller's Day Off (1986)",
  "Predator (1987)",
  "The Little Mermaid (1989)",
  "Dead Poets Society (1989)",
  "The Thing (1982)",
  "Weekend at Bernie's (1989)",
  "Heathers (1988)",
  "The Terminator (1984)",
  "Ghostbusters II (1989)",
  "Once Upon a Time in America (1984)",
  "Coming to America (1988)",
  "Indiana Jones and the Last Crusade (1989)",
  "The Blue Lagoon (1980)",
  "Airplane! (1980)",
  "Fast Times at Ridgemont High (1982)",
  "Indiana Jones and the Temple of Doom (1984)",
  "TRON (1982)",
  "Caddyshack (1980)",
  "Beverly Hills Cop (1984)",
  "The Evil Dead (1981)",
  "Highlander (1986)",
  "The NeverEnding Story (1984)",
  "The Shawshank Redemption (1994)",
  "Jumanji (1995)",
  "The Silence of the Lambs (1991)",
  "The Lion King (1994)",
  "Titanic (1997)",
  "Eyes Wide Shut (1999)",
  "The Professional (1994)",
  "The Matrix (1999)",
  "Deep Impact (1998)",
  "Newsies (1992)",
  "Casino (1995)",
  "The Green Mile (1999)",
  "Fight Club (1999)",
  "Jurassic Park (1993)",
  "Saving Private Ryan (1998)",
  "The Fifth Element (1997)",
  "The Big Lebowski (1998)",
  "American Pie (1999)",
  "Beauty and the Beast (1991)",
  "Se7en (1995)",
  "10 Things I Hate About You (1999)",
  "The Godfather: Part III (1990)",
  "Toy Story (1995)",
  "Boogie Nights (1997)",
  "Cruel Intentions (1999)",
  "Romeo + Juliet (1996)",
  "The Usual Suspects (1995)",
  "Good Will Hunting (1997)",
  "Heat (1995)",
  "Star Wars: Episode I - The Phantom Menace (1999)",
  "American History X (1998)",
  "The Mummy (1999)",
  "Clueless (1995)",
  "Reservoir Dogs (1992)",
  "Basic Instinct (1992)",
  "Magnolia (1999)",
  "The Sixth Sense (1999)",
  "The Truman Show (1998)",
  "Waterworld (1995)",
  "Terminator 2 (1991)",
  "Trainspotting (1996)",
  "Dazed and Confused (1993)",
  "Pretty Woman (1990)"
];

let countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua & Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia & Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Cote D'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestinian State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Samoa",
  "San Marino",
  "Sao Tome & Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "St. Kitts & Nevis",
  "St. Lucia",
  "St. Vincent & The Grenadines",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "The Netherlands",
  "The Philippines",
  "Togo",
  "Tonga",
  "Trinidad & Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States Of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];

let capitals = [
  "Kabul", "Tirana", "Algiers", "Andorra la Vella", "Luanda", "St. John's", "Buenos Aires", "Yerevan", "Canberra", 
  "Vienna", "Baku", "Nassau", "Manama", "Dhaka", "Bridgetown", "Minsk", "Brussels", "Belmopan", "Porto-Novo", 
  "Thimphu", "La Paz", "Sarajevo", "Gaborone", "Brasília", "Bandar Seri Begawan", "Sofia", "Ouagadougou", 
  "Bujumbura", "Phnom Penh", "Yaoundé", "Ottawa", "Praia", "Bangui", "N'Djamena", "Santiago", "Beijing", "Bogotá", 
  "Moroni", "Kinshasa", "San José", "Yamoussoukro", "Zagreb", "Havana", "Nicosia", "Prague", "Copenhagen", 
  "Djibouti", "Roseau", "Santo Domingo", "Dili", "Quito", "Cairo", "San Salvador", "Malabo", "Asmara", "Tallinn", 
  "Mbabane", "Addis Ababa", "Suva", "Helsinki", "Paris", "Libreville", "Banjul", "Tbilisi", "Berlin", "Accra", 
  "Athens", "St. George's", "Guatemala City", "Conakry", "Bissau", "Georgetown", "Port-au-Prince", "Tegucigalpa", 
  "Budapest", "Reykjavík", "New Delhi", "Jakarta", "Tehran", "Baghdad", "Dublin", "Jerusalem", "Rome", "Kingston", 
  "Tokyo", "Amman", "Nur-Sultan", "Nairobi", "Tarawa", "Pristina", "Kuwait City", "Bishkek", "Vientiane", "Riga", 
  "Beirut", "Maseru", "Monrovia", "Tripoli", "Vaduz", "Vilnius", "Luxembourg", "Skopje", "Antananarivo", "Lilongwe", 
  "Kuala Lumpur", "Malé", "Bamako", "Valletta", "Majuro", "Nouakchott", "Port Louis", "Mexico City", "Palikir", 
  "Chişinău", "Monaco", "Ulaanbaatar", "Podgorica", "Rabat", "Maputo", "Naypyidaw", "Windhoek", "Yaren", "Kathmandu", 
  "Wellington", "Managua", "Niamey", "Abuja", "Pyongyang", "Oslo", "Muscat", "Islamabad", "Ngerulmud", "Ramallah", 
  "Panama City", "Port Moresby", "Asunción", "Lima", "Warsaw", "Lisbon", "Doha", "Brazzaville", "Bucharest", 
  "Moscow", "Kigali", "Apia", "San Marino", "São Tomé", "Riyadh", "Dakar", "Belgrade", "Victoria", "Freetown", 
  "Singapore", "Bratislava", "Ljubljana", "Honiara", "Mogadishu", "Pretoria", "Seoul", "Juba", "Madrid", 
  "Sri Jayawardenepura Kotte", "Basseterre", "Castries", "Kingstown", "Khartoum", "Paramaribo", "Stockholm", 
  "Bern", "Damascus", "Taipei", "Dushanbe", "Dodoma", "Bangkok", "Amsterdam", "Manila", "Lomé", "Nuku'alofa", 
  "Port of Spain", "Tunis", "Ankara", "Ashgabat", "Funafuti", "Kampala", "Kiev", "Abu Dhabi", "London", 
  "Washington, D.C.", "Montevideo", "Tashkent", "Port Vila", "Vatican City", "Caracas", "Hanoi", "Sana'a", 
  "Lusaka", "Harare"
]

let moods= [
		"abandoned",
		"absent minded",
		"abused",
		"accepted",
		"accomplished",
		"accusatory",
		"accused",
		"admired",
		"adored",
		"adrift",
		"affectionate",
		"afraid",
		"aggravated",
		"aggressive",
		"agitated",
		"alarmed",
		"alert",
		"alienated",
		"alive",
		"alluring",
		"alone",
		"aloof",
		"amazed",
		"ambushed",
		"amused",
		"angry",
		"annoyed",
		"antagonistic",
		"anxious",
		"apathetic",
		"apologetic",
		"appalled",
		"appreciated",
		"appreciative",
		"apprehensive",
		"aroused",
		"ashamed",
		"astonished",
		"attacked",
		"attractive",
		"awake",
		"aware",
		"awe",
		"awed",
		"awestruck",
		"awkward",
		"bad",
		"baffled",
		"barren",
		"bashful",
		"beaten",
		"belittled",
		"benevolent",
		"berated",
		"betrayed",
		"bewildered",
		"bitchy",
		"bitter",
		"bittersweet",
		"blah",
		"blamed",
		"blank",
		"blissful",
		"blue",
		"bold",
		"bored",
		"bothered",
		"bouncy",
		"brave",
		"broken",
		"brooding",
		"bummed",
		"burdened",
		"burned-out",
		"callous",
		"calm",
		"capable",
		"carefree",
		"careless",
		"caring",
		"caustic",
		"cautious",
		"censored",
		"centered",
		"certain",
		"challenged",
		"charmed",
		"cheated",
		"cheerful",
		"cherished",
		"childish",
		"chipper",
		"choleric",
		"clean",
		"clear",
		"clever",
		"close",
		"closed",
		"clueless",
		"clumsy",
		"cold",
		"comfortable",
		"committed",
		"compassionate",
		"competent",
		"competitive",
		"complacent",
		"complete",
		"concerned",
		"condemned",
		"condescension",
		"confident",
		"confining",
		"confused",
		"considerate",
		"contemplative",
		"contempt",
		"contemptuous",
		"content",
		"controlled",
		"conventional",
		"convicted",
		"cornered",
		"courageous",
		"cowardly",
		"cranky",
		"crappy",
		"crazy",
		"critical",
		"cross",
		"crushed",
		"curious",
		"cynical",
		"daring",
		"dark",
		"dashed",
		"dazed",
		"dead",
		"deceived",
		"dedicated",
		"defeated",
		"defenseless",
		"defensive",
		"defiant",
		"degraded",
		"dejected",
		"delicate",
		"delighted",
		"demoralized",
		"dependent",
		"depressed",
		"deprived",
		"derisive",
		"deserted",
		"desired",
		"desolate",
		"despair",
		"desperate",
		"destroyed",
		"detached",
		"determined",
		"devastated",
		"devious",
		"devoted",
		"didactic",
		"different",
		"difficult",
		"dignified",
		"dirty",
		"disappointed",
		"disbelieving",
		"discarded",
		"disconnected",
		"discontent",
		"discontented",
		"discouraged",
		"disdainful",
		"disgraced",
		"disgusted",
		"disheartened",
		"dishonest",
		"disillusioned",
		"dismal",
		"dismayed",
		"disobedient",
		"disorganized",
		"disposable",
		"distant",
		"distracted",
		"distressed",
		"disturbed",
		"ditzy",
		"dorky",
		"doubtful",
		"down",
		"drained",
		"dreamy",
		"dreary",
		"dropped",
		"drunk",
		"dull",
		"dumb",
		"eager",
		"earnest",
		"ecstatic",
		"edgy",
		"effective",
		"elated",
		"embarassed",
		"embarrassed",
		"empathetic",
		"empowered",
		"empty",
		"enchanted",
		"encouraged",
		"energetic",
		"energized",
		"enlightened",
		"enraged",
		"enriched",
		"entertained",
		"enthralled",
		"enthusiastic",
		"envious",
		"erudite",
		"evasive",
		"evil",
		"exasperated",
		"excited",
		"excluded",
		"exhausted",
		"exhilarated",
		"expectant",
		"exploited",
		"exposed",
		"exuberant",
		"faithful",
		"fake",
		"fanciful",
		"fantastic",
		"fatalistic",
		"fatigued",
		"fearful",
		"fearless",
		"feisty",
		"fine",
		"flirty",
		"flustered",
		"foolish",
		"foreboding",
		"forgiven",
		"forgiving",
		"forgotten",
		"forthright",
		"fortunate",
		"framed",
		"frantic",
		"free",
		"friendly",
		"frightened",
		"frisky",
		"frustrated",
		"fulfilled",
		"full",
		"funny",
		"furious",
		"futile",
		"geeky",
		"generous",
		"gentle",
		"giddy",
		"giggly",
		"giving",
		"glad",
		"gloomy",
		"glorious",
		"good",
		"grateful",
		"great",
		"grieving",
		"groggy",
		"grouchy",
		"grumpy",
		"guarded",
		"guilty",
		"gullible",
		"handicapped",
		"happy",
		"harmonious",
		"hateful",
		"haughty",
		"haunted",
		"haunting",
		"healthy",
		"heard",
		"heartbroken",
		"heavy-hearted",
		"helpful",
		"helpless",
		"hesitant",
		"high",
		"honored",
		"hopeful",
		"hopeless",
		"horrible",
		"horrified",
		"hospitable",
		"hostile",
		"hot",
		"humble",
		"humiliated",
		"hungry",
		"hurt",
		"hyper",
		"hysterical",
		"idealistic",
		"idiotic",
		"idyllic",
		"ignorant",
		"ignored",
		"imaginative",
		"immune",
		"impatient",
		"impelled",
		"imperfect",
		"impertinent",
		"important",
		"impressed",
		"impulsive",
		"inadequate",
		"inattentive",
		"incensed",
		"inclusive",
		"incompetent",
		"incomplete",
		"incredulous",
		"indebted",
		"indecisive",
		"independent",
		"indescribable",
		"indifferent",
		"indignant",
		"industrious",
		"inept",
		"inferior",
		"inflated",
		"informed",
		"infuriated",
		"inhibited",
		"innocent",
		"innovative",
		"inquisitive",
		"insane",
		"insecure",
		"insensitive",
		"insidious",
		"insignificant",
		"insulted",
		"intense",
		"interested",
		"interrogated",
		"interrupted",
		"intimate",
		"intimidated",
		"intrigued",
		"invigorated",
		"invisible",
		"involved",
		"irate",
		"irked",
		"irrational",
		"irresponsible",
		"irritated",
		"isolated",
		"jaded",
		"jealous",
		"jinxed",
		"jolly",
		"jovial",
		"joyful",
		"joyous",
		"jubilant",
		"judged",
		"judgmental",
		"jumpy",
		"just",
		"justified",
		"kidded",
		"kind",
		"knowledgeable",
		"late",
		"lazy",
		"leery",
		"left",
		"let",
		"lethargic",
		"liable",
		"liberated",
		"liberating",
		"lifeless",
		"light-hearted",
		"liked",
		"listened",
		"listless",
		"logical",
		"lonely",
		"loose",
		"lost",
		"lousy",
		"lovable",
		"loved",
		"loving",
		"lucky",
		"lyrical",
		"mad",
		"malicious",
		"manipulated",
		"matter",
		"fact",
		"mean",
		"meditative",
		"melancholic",
		"melancholy",
		"mellow",
		"merciless",
		"merry",
		"mischievous",
		"miserable",
		"misinterpreted",
		"mistreated",
		"misunderstood",
		"mixed",
		"mocked",
		"mocking",
		"modest",
		"molested",
		"moody",
		"morose",
		"motivated",
		"mournful",
		"moved",
		"mystified",
		"naive",
		"nasty",
		"naughty",
		"nauseated",
		"needed",
		"needy",
		"negative",
		"neglected",
		"nerdy",
		"nervous",
		"neurotic",
		"nightmarish",
		"nonchalant",
		"nostalgic",
		"not",
		"specified",
		"noticed",
		"numb",
		"obeyed",
		"objective",
		"obligated",
		"obvious",
		"odd",
		"offended",
		"okay",
		"old",
		"open",
		"oppressed",
		"optimistic",
		"ornery",
		"control",
		"outraged",
		"overcome",
		"overjoyed",
		"overloaded",
		"overwhelmed",
		"overworked",
		"owned",
		"painful",
		"pampered",
		"panicky",
		"paralyzed",
		"passionate",
		"passive",
		"patient",
		"patronizing",
		"peaceful",
		"peeved",
		"pensive",
		"perky",
		"perplexed",
		"persecuted",
		"pessimistic",
		"pestered",
		"petrified",
		"petty",
		"phony",
		"pious",
		"pissed",
		"off",
		"playful",
		"pleased",
		"poor",
		"positive",
		"possessive",
		"powerful",
		"powerless",
		"practical",
		"predatory",
		"pressured",
		"private",
		"productive",
		"protected",
		"protective",
		"proud",
		"provoked",
		"prudish",
		"punished",
		"pushy",
		"puzzled",
		"questioned",
		"quiet",
		"quixotic",
		"quizzical",
		"rambunctious",
		"realistic",
		"reassured",
		"rebellious",
		"reborn",
		"receptive",
		"reckless",
		"recognized",
		"reconciled",
		"recumbent",
		"reflective",
		"refreshed",
		"regretful",
		"rejected",
		"rejuvenated",
		"relaxed",
		"released",
		"relieved",
		"reluctant",
		"reminiscent",
		"remorse",
		"renewed",
		"replaced",
		"replenished",
		"repressed",
		"rescued",
		"resentful",
		"reserved",
		"resistant",
		"resourceful",
		"respected",
		"responsible",
		"restless",
		"restricted",
		"revengeful",
		"reverent",
		"revitalized",
		"ribald",
		"rich",
		"ridicule",
		"ridiculous",
		"right",
		"rigid",
		"robbed",
		"romantic",
		"rotten",
		"rushed",
		"sabotaged",
		"sad",
		"safe",
		"sarcastic",
		"sardonic",
		"sassy",
		"satiated",
		"satiric",
		"satisfied",
		"saved",
		"scared",
		"scolded",
		"scorned",
		"secure",
		"seductive",
		"selfish",
		"self-assured",
		"self-centered",
		"self-confident",
		"self-conscious",
		"self-destructive",
		"self-reliant",
		"sensitive",
		"sentimental",
		"serene",
		"serious",
		"sexy",
		"shaken",
		"shamed",
		"sheepish",
		"shocked",
		"shunned",
		"shy",
		"sick",
		"silenced",
		"silly",
		"sincere",
		"sinful",
		"skeptical",
		"skillful",
		"slandered",
		"sleepy",
		"sluggish",
		"small",
		"smart",
		"smothered",
		"solemn",
		"somber",
		"soothed",
		"sorry",
		"special",
		"spiteful",
		"splendid",
		"spunky",
		"squashed",
		"stifled",
		"stimulated",
		"stingy",
		"strained",
		"stressed",
		"stretched",
		"strong",
		"stubborn",
		"stumped",
		"stunned",
		"stupid",
		"submissive",
		"successful",
		"suffocated",
		"suicidal",
		"sullen",
		"sunk",
		"super",
		"superior",
		"supported",
		"sure",
		"surly",
		"surprised",
		"suspenseful",
		"suspicious",
		"sympathetic",
		"tacky",
		"tactful",
		"talented",
		"talkative",
		"tame",
		"tarnished",
		"tasteful",
		"tearful",
		"teased",
		"tenacious",
		"tender",
		"tense",
		"tepid",
		"terrible",
		"terrific",
		"terrified",
		"terrifying",
		"tested",
		"testy",
		"thankful",
		"thoughtful",
		"threatened",
		"threatening",
		"thrifty",
		"thrilled",
		"tired",
		"tormented",
		"torn",
		"tortured",
		"touched",
		"tough",
		"tragic",
		"tranquil",
		"transformed",
		"trapped",
		"treasured",
		"trembly",
		"tremendous",
		"tricked",
		"troubled",
		"trusted",
		"trustful",
		"ugly",
		"unaccepted",
		"unappreciated",
		"unbalanced",
		"unburdened",
		"uncanny",
		"uncomfortable",
		"unconcerned",
		"uneven",
		"unfit",
		"unfriendly",
		"united",
		"unjust",
		"unknown",
		"unneeded",
		"unpleasant",
		"unreal",
		"unruly",
		"unwise",
		"up",
		"uplifted",
		"used",
		"useless",
		"vacant",
		"vague",
		"vain",
		"valid",
		"valued",
		"vengeful",
		"vexed",
		"vicious",
		"victimized",
		"victorious",
		"violated",
		"violent",
		"vivacious",
		"vivid",
		"void",
		"wacky",
		"warlike",
		"warm",
		"warmhearted",
		"warned",
		"wary",
		"wasted",
		"weak",
		"wealthy",
		"weary",
		"weird",
		"welcoming",
		"whimsical",
		"whole",
		"wild",
		"willful",
		"wishful",
		"witty",
		"worldly",
		"worried",
		"worse",
		"worthy",
		"wounded",
		"wrong",
		"yearning",
		"yellow",
		"yielding",
		"young",
		"youthful",
		"zany",
		"zealous"
	]
